# These are supported funding model platforms

github: [Incrisz]  # Replace with your GitHub username
# patreon: # Replace with your Patreon username if applicable
# open_collective: # Replace with your Open Collective username if applicable
# ko_fi: # Replace with your Ko-fi username if applicable
# custom: ["https://your-custom-link.com"]
